# Use root/example as user/password credentials
version: "3.1"
services:
  mysql-db:
    image: mysql/mysql-server:5.7
    container_name: mysql_DB_container
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpwd
      MYSQL_DATABASE: database_development
volumes:
  db_data:
